### ISSUE TITLE
Prevent cube generation without quality band set

### ISSUE THREAD

**Issue by raphaelrpl** [brazil-data-cube/cube-builder#72]
The following error occurs when dispatch data cube without quality band:

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/app/cube_builder/celery/__init__.py", line 67, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/cube_builder/tasks.py", line 180, in prepare_blend
    efficacy, cloudratio = quality_date_stats[_merge['date']]
```

The code seems right, however, we must to prevent the cube generation when quality is not set.

**Comment by raphaelrpl** [comment]
Resolved in e13779035635f378999311e74b3022ef1458934d
